language: java
jdk:
  - oraclejdk8
branches:
  only:
    - benchmarking
notifications:
  email:
    recipients:
      - esteves@informatik.uni-leipzig.de
    on_success: change
    on_failure: change
after_success:
  - mvn clean 
